inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - 'spec/dummy/db/**/*.rb'
    - 'vendor/**/*'
    - 'gemfiles/*'
    - 'tests/test-app/**/*'
    - 'tests/backend-test/**/*'

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineEndStringConcatenationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'logux-rack.gemspec'
    - 'lib/logux/test/helpers.rb'

Metrics/MethodLength:
  Max: 15

Metrics/ParameterLists:
  CountKeywordArgs: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/logux/tasks/*.rb'
    - 'spec/requests/*.rb'

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/MultipleMemoizedHelpers:
  Max: 10

Style/DateTime:
  Enabled: false

Style/Documentation:
  Enabled: false
