inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - 'spec/dummy/db/**/*.rb'
    - 'vendor/**/*'
    - 'gemfiles/*'
    - 'tests/test-app/**/*'
    - 'tests/backend-test/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'logux-rack.gemspec'
    - 'lib/logux/test/helpers.rb'

Metrics/ParameterLists:
  CountKeywordArgs: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/logux/tasks/*.rb'
    - 'spec/requests/*.rb'

FactoryBot/StaticAttributeDefinedDynamically:
  Enabled: false

RSpec/ExpectChange:
  EnforcedStyle: block

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/DateTime:
  Enabled: false
