version: '3.4'

services:
  app:
    image: ruby:2
    environment:
      - BUNDLE_PATH=/bundle
      - BUNDLE_CONFIG=/app/.bundle/config
      - DB_HOST=db
      - DB_NAME=logux_rack
      - DB_USERNAME=postgres
    command: bash
    working_dir: /app
    volumes:
      - .:/app:cached
      - bundler_data:/bundle
    tmpfs:
      - /tmp

volumes:
  bundler_data:
