version: '3.4'

services:
  app:
    image: ruby:2
    environment:
      - BUNDLE_PATH=/bundle
    command: bash
    working_dir: /app
    volumes:
      - .:/app:cached
      - bundle:/bundle
    tmpfs:
      - /tmp

volumes:
  bundle:
