# This workflow integrates Brakeman with GitHub's Code Scanning feature
# Brakeman is a static analysis security vulnerability scanner for Ruby on Rails applications

name: Brakeman

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  brakeman-scan:
    name: Brakeman
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - uses: devmasx/brakeman-linter-action@v1.0.0
