name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2

      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: gems-${{ runner.os }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: gems-${{ runner.os }}-

      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install

      - name: Run RuboCop
        run: bundle exec rubocop --parallel

  reek:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2

      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: gems-${{ runner.os }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: gems-${{ runner.os }}-

      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install

      - name: Run Reek
        run: bundle exec reek --single-line .

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_DB: "logux_rack_test"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2

      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: gems-${{ runner.os }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: gems-${{ runner.os }}-

      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install

      - name: Install PostgreSQL client
        run: |
          sudo apt-get --yes install libpq-dev

      - name: Run tests
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/logux_rack_test"
        run: |
          bundle exec rspec

      - name: Upload code coverage
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: coverage/
